export declare function event(name: any, parameters?: {}): void;
export declare function onError(e: any): void;
export declare function baselineText(text: any, parameters: any): any;
export declare function trimDefinition(name: any): any;
export declare function mapcat(f: any, coll: any): any;
export declare function abstract(): any;
export declare function ucfirst(s: string): string;
export declare function pad(s: string, c: string, n: number): any;
export declare function padTime(n: number): string;
export declare function numericText(n: any, withDecimal?: boolean): any;
export declare function addComaToNumericNumber(s: string, withDecimal?: boolean): any;
export declare function calculateIntersection(rect1: any, rect2: any, x: any, y: any): {
    width: number;
    height: number;
};
export declare function calculateCollision(obj: any, direction: any, collideables: any, moveBy: any): any;
export declare function lineLength(a: createjs.Point, b: createjs.Point): number;
export declare function lineAngle(a: createjs.Point, b: createjs.Point): number;
export declare function deg2rad(n: number): number;
export declare function rad2deg(n: number): number;
export declare function clamp(x: number, min: number, max: number): number;
export declare function between(x: number, min: number, max: number): boolean;
export declare function round(precision: number, value: number): any;
export declare var round2: Function;
export declare function localToLocalCoordinate(containerFrom: createjs.Container, containerTo: createjs.Container, origin: createjs.Point): createjs.Point;
export declare function listen(type: any, callback: any): void;
export declare function unlisten(type: any, callback: any): void;
export declare function isMobile(): boolean;
export declare var urlParams: Function;
export declare var os: Function;
export declare var browser: Function;
